.TH FLL_FSHELPER "8" "August 2007" "" ""
.SH NAME
fll_fshelper \- fstab and mountpoint helper
.SH SYNOPSIS
\fBfll_fshelper\fR \fI<options>\fR
.SH DESCRIPTION
\fIrebuildfstab\fR is intended for initial creation of \fI/etc/fstab\fR by
live linux distro's. It is not intended for ongoing maintenance of the
fstab file on standard linux distro installations.
.PP
.SH OPTIONS
.TP
\fB\-h|\-\-help\fR
print help screen
.TP
\fB\-w|\-\-write\-fstab\fR
(re)create the fstab file
.TP
\fB\-m|\-\-make\-mountpoints\fR
(re)create mountpoints in /media
.TP
\fB\-\-no\-swap\fR
don't write fstab entry for swap partitions
.TP
\fB\-u|\-\-uuids\fR
use UUID's for mount names when possible
.TP
\fB\-l|\-\-labels\fR
use LABELS's for mount names when possible
.TP
\fB\-f|\-\-fstab\fR \fI<file>\fR
target file to write output to
.TP
\fB\-a|\-\-auto\fR
set auto mount option where applicable
.TP
\fB\-q|\-\-quiet\fR
surpress output when writing to file
.TP
\fB\-d|\-\-debug\fR
enable debug output
.PP
.SH AUTHOR
This manual page was written by Kel Modderman <kel@otaku42.de> for
the Debian GNU system (but may be used by others).
