.TH FLL_LOGIN "1" "May 2007" "" ""
.SH NAME
fll_login \- fll live inittab login wrapper for /bin/login
.SH SYNOPSIS
\fBfll_login\fR
.SH DESCRIPTION
The purpose of \fIfll_login\fR is to provide a wrapper around \fI/bin/login\fR
when booting from fll live media with passwordless root and user accounts.
.PP
\fIfll_login\fR will source \fI/etc/default/distro\fR in order to get the
\fIFLL_LIVE_USER\fR shell variable, check with getent the validity of the
\fIFLL_LIVE_USER\fR user account and finally login as that user using the login
option for preauthentication (i.e. \fBexec /bin/login \-f $FLL_LIVE_USER\fR).
.PP
If the user specified by \fIFLL_LIVE_USER\fR is invalid, login as root instead.
.PP
\fIfll_login\fR takes no options.
.PP
.SH AUTHOR
This manual page was written by Kel Modderman <kel@otaku42.de> for
the Debian GNU system (but may be used by others).
