#!/bin/sh

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -r /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

[ -x "$(which homectl)" ] || exit 0

if [ -d "/home/${FLL_LIVE_USER}" ] || \
   [ -e "/home/${FLL_LIVE_USER}.homedir" ]; then
	exit 0
fi

homectl create "${FLL_LIVE_USER}" \
	--real-name="${FLL_LIVE_USER}" \
	--member-of="${FLL_LIVE_USER_GROUPS}" \
	--session-launcher="${FLL_XSESSION}" \
	--session-type="${FLL_XTYPE}" \
	--auto-login=on
