#!/bin/sh

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -r /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

[ -x "$(which homectl)" ] || exit 0
[ -e "/home/${FLL_LIVE_USER}" ] && exit 0

homectl create "${FLL_LIVE_USER}" \
	--storage=directory \
	--real-name="${FLL_LIVE_USER}" \
	--member-of="${FLL_LIVE_USER_GROUPS}" \
	--auto-login=on \
	--session-launcher="${FLL_XSESSION}" \
	--session-type="${FLL_XTYPE}"
