#!/bin/sh

# Description:       The purpose of this script is to detect and configure an
#                    installed X desktop manager (i.e. sddm, lightdm, gdm3 etc.).

###
# F.U.L.L.S.T.O.R.Y
#
# Copyright: (C) 2007-2024 Kel Modderman <kelvmod@gmail.com>
# Copyright: (C) 2007-2024 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# Copyright: (C) 2016 Niall Walsh <niallwalsh@celtux.org>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# https://github.com/fullstory
###

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -r /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

setup_gdm3() {
	# autologin + greeter theme
	# timed login required for login after x restart
	sed -i	-e "/^AutomaticLogin\=.*/d" \
		-e "/^AutomaticLoginEnable\=.*/d" \
		-e "/^TimedLoginEnable\=.*/d" \
		-e "/^TimedLogin\=.*/d" \
		-e "/^TimedLoginDelay\=.*/d" \
		-e "s/^\(\[daemon\]$\)/\1\nAutomaticLogin\=${FLL_LIVE_USER}\nAutomaticLoginEnable\=true\n \
			\nTimedLoginEnable\=true\nTimedLogin\=${FLL_LIVE_USER}\nTimedLoginDelay\=1/" \
			/etc/gdm3/daemon.conf
}

setup_lightdm() {
	# set autologin user and set timeout to zero
	mkdir -p /etc/lightdm/lightdm.conf.d
	if [ ! -e /etc/lightdm/lightdm.conf.d/80_fll-live-initscripts.conf ]; then
		cat >/etc/lightdm/lightdm.conf.d/80_fll-live-initscripts.conf <<EOF
[SeatDefaults]
greeter-hide-users=false
autologin-user=${FLL_LIVE_USER}
autologin-user-timeout=0
EOF
	fi
}

setup_lxdm() {
	# set autologin user
	if [ -L /etc/lxdm/default.conf ] && [ ! -e /etc/lxdm/live.conf ]; then
		rm -f /etc/lxdm/default.conf
		sed "s/^# autologin=.*/&\nautologin=${FLL_LIVE_USER}/" \
			/etc/lxdm/lxdm.conf >/etc/lxdm/live.conf
		ln -fs live.conf /etc/lxdm/default.conf
	fi
}

setup_sddm() {
	printf "[General]\nDisplayServer=${FLL_XTYPE}\n\n" \
		>/etc/sddm.conf
	printf "[Autologin]\nRelogin=true\n\nSession=${FLL_XSESSION}.desktop\nUser=${FLL_LIVE_USER}\n" \
		>>/etc/sddm.conf
}

setup_slim() {
	# set autologin for $FLL_LIVE_USER to yes
	sed -i	-e "s/^default_user.*/\#FLL\#&/" \
		-e "s/^\#FLL\#\(default_user[ \t]*${FLL_LIVE_USER}$\)/\1/" \
		-e "s/^auto_login.*/\#FLL\#&/" \
		-e "s/^\#FLL\#\(auto_login[ \t]*yes$\)/\1/" \
			/etc/slim.conf
	grep -q ^default_user /etc/slim.conf || \
		printf "default_user\t${FLL_LIVE_USER}\n" >> /etc/slim.conf
	grep -q ^auto_login /etc/slim.conf || \
		printf "auto_login\tyes\n" >> /etc/slim.conf
}

setup_x_cursor_theme() {
	if [ -e /usr/share/icons/DMZ-Black/cursor.theme ]; then
		update-alternatives --set x-cursor-theme /usr/share/icons/DMZ-Black/cursor.theme >/dev/null
	fi
}

setup_dm() {
	SLIM="$(which slim 2>/dev/null)"
	if [ -x "${SLIM}" ]; then
		echo "configuring slim"
		setup_slim
	fi

	GDM3="$(which gdm3 2>/dev/null)"
	if [ -x "${GDM3}" ]; then
		echo "configuring gdm3"
		setup_gdm3
	fi

	LXDM="$(which lxdm 2>/dev/null)"
	if [ -x "${LXDM}" ]; then
		echo "configuring lxdm"
		setup_lxdm
	fi

	LIGHTDM="$(which lightdm 2>/dev/null)"
	if [ -x "${LIGHTDM}" ]; then
		echo "configuring lightdm"
		setup_lightdm
	fi

	SDDM="$(which sddm 2>/dev/null)"
	if [ -x "${SDDM}" ]; then
		echo "configuring sddm"
		setup_sddm
	fi
}

setup_x_cursor_theme
setup_dm
