#!/bin/sh

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -r /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

[ -x "$(which homectl)" ] || exit 0

HOMECTL=$(homectl list -EE | jq '.[] | select(.name=="'${FLL_LIVE_USER}'")')
if [ -n "${HOMECTL}" ]; then
	HOMECTL_STATE=$(echo "${HOMECTL}" | jq -r '.state')
	case "${HOMECTL_STATE}" in
		unfixated|inactive)
			[ "${HOMECTL_STATE}" = "unfixated" ] && \
				homectl activate "${FLL_LIVE_USER}"
			homectl update --offline "${FLL_LIVE_USER}" \
				--member-of="${FLL_LIVE_USER_GROUPS}" \
				--session-launcher="${FLL_XSESSION}" \
				--session-type="${FLL_XTYPE}"
			;;
	esac
else
	homectl create "${FLL_LIVE_USER}" \
		--real-name="${FLL_LIVE_USER}" \
		--member-of="${FLL_LIVE_USER_GROUPS}" \
		--session-launcher="${FLL_XSESSION}" \
		--session-type="${FLL_XTYPE}" \
		--storage=directory
fi
