#!/bin/sh

# only run in live environment
[ -d "${FLL_MOUNTPOINT}" ] || exit 0

adduser --disabled-password --gecos "${FLL_LIVE_USER}" "${FLL_LIVE_USER}"

. /usr/share/fll-live-initscripts/setup_sudo
setup_sudo

# setup autologin for passwdless live user
. /usr/share/fll-live-initscripts/setup_display_manager_autologin
setup_display_manager_autologin
