#!/bin/sh

setup_skel() {
    FACE=/usr/share/icons/hicolor/scalable/apps/aptosid-fred.svg
    [ -f "${FACE}" ] && cp ${FACE} /etc/skel/.face

    case "${FLL_XSESSION}" in
        labwc)
            . /etc/default/keyboard
            if [ "${XKBVARIANT}" ]; then
                XKB_DEFAULT_LAYOUT="${XKBLAYOUT}(${XKBVARIANT})"
            else
                XKB_DEFAULT_LAYOUT="${XKBLAYOUT}"
            fi
            cat >> /etc/xdg/labwc/environment <<EOF
XKB_DEFAULT_LAYOUT="${XKB_DEFAULT_LAYOUT}"
EOF
            ;;
    esac
}
