#!/bin/sh

setup_passwdless_live_user() {
    # Create sudoers.d snippet
    if [ ! -e "/etc/sudoers.d/15_${FLL_DISTRO_NAME}" ]; then
        # append sudoers entry
        cat >> "/etc/sudoers.d/15_${FLL_DISTRO_NAME}" <<EOF
# WARNING: This allows the unprivileged ${FLL_LIVE_USER} user to start commands as root
# WARNING: This is totally insecure and (almost) makes ${FLL_LIVE_USER} a second root account.
# WARNING: Never allow external access to the ${FLL_LIVE_USER} user!!!
${FLL_LIVE_USER} ALL=(ALL:ALL) NOPASSWD: ALL
EOF
        chmod 0440 "/etc/sudoers.d/15_${FLL_DISTRO_NAME}"
    fi

    # disable screen lock for passwdless live user
    case "${FLL_XSESSION}" in
        plasma*)
            cat >> /etc/xdg/kscreenlockerrc <<EOF
[Daemon]
Autolock=false
LockOnResume=false
EOF
            ;;
        gnome)
            sudo -u "${FLL_LIVE_USER}" dbus-run-session -- gsettings set \
                org.gnome.desktop.screensaver lock-enabled false
            ;;
        xfce)
            if ! grep -qs "^lock:" "/home/${FLL_LIVE_USER}/.xscreensaver"; then
                echo "lock: False" >> "/home/${FLL_LIVE_USER}/.xscreensaver"
                chown "${FLL_LIVE_USER}:${FLL_LIVE_USER}" \
                    "/home/${FLL_LIVE_USER}/.xscreensaver"
            fi
            ;;
        cinnamon)
            sudo -u "${FLL_LIVE_USER}" dbus-run-session -- gsettings set \
                org.cinnamon.desktop.lockdown disable-lock-screen true
            ;;
    esac
}
