#!/bin/sh
###############################################################################
# 	configure sudo for passwdless live user
###############################################################################
setup_sudo() {
    # Create sudoers.d snippet
    if [ ! -e "/etc/sudoers.d/15_${FLL_DISTRO_NAME}" ]; then
        # append sudoers entry
        cat >> "/etc/sudoers.d/15_${FLL_DISTRO_NAME}" <<EOF
# WARNING: This allows the unprivileged ${FLL_LIVE_USER} user to start commands as root
# WARNING: This is totally insecure and (almost) makes ${FLL_LIVE_USER} a second root account.
# WARNING: Never allow external access to the ${FLL_LIVE_USER} user!!!
${FLL_LIVE_USER} ALL=(ALL:ALL) NOPASSWD: ALL
EOF
        chmod 0440 "/etc/sudoers.d/15_${FLL_DISTRO_NAME}"
    fi

    # also disable kscreenlock for passwdless live user
    case "${FLL_XSESSION}" in
        plasma*)
            cat >> /etc/xdg/kscreenlockerrc <<EOF
[Daemon]
Autolock=false
LockOnResume=false
EOF
            ;;
    esac
}
